### PR TITLE
Added dynamodb tests permissions

### PR DESCRIPTION
**Pull request by marknet15**
## Overview
I've raised this as requested (linked below) in order to move over a pull request from ansible to the new aws collections repo:
https://github.com/ansible-collections/community.aws/pull/65

https://github.com/ansible/ansible/pull/68320#issuecomment-623299135

### CODE REVIEW

**Comment by marknet15** [comment]
Hi @tremble, would you be able to review this ? I've drafted a new PR as requested to the new aws community collections repo, and I think this here PR is the missing piece to getting the tests to pass :)

**Comment by tremble** [comment]
@marknet15 permissions look sane on my side.

That covers making them available to devs you'll need to tweak a second file (aws/policy/data-services.yaml) to make them available to CI.

For what it's worth, I agree it's annoying to update in two places with two formats.  I have a PR in place to make this more consistent.

CC: @jillr (who can actually merge this)

**Comment by marknet15** [comment]
@tremble awesome thanks, so I've had a look at https://github.com/mattclay/aws-terminator/blob/master/aws/policy/data-services.yaml and updated it to hold the permissions i added in the other file.

That's nice to hear :) not a huge problem at any rate

**Comment by tremble** [comment]
Just to set expectations: @jillr generally does the merges on this repo (although mattclay and s-hertel can too), and _generally_ reviews the PR queue for this repo on Thursdays...

**Comment by jillr** [comment]
@marknet15 I saw your comment in the other PR about picking this back up, you'll also need to resolve the git conflicts in this PR please.

**Pull request closed without merging**
