### PR TITLE
Adds permissions for running aws_codecommit integration tests

### PR DESCRIPTION
**Pull request by caphrim007**

### CODE REVIEW

**Comment by caphrim007** [comment]
required to unblock https://github.com/ansible/ansible/pull/61263

**Comment by s-hertel** [comment]
@jillr is going to deploy this. Thanks @caphrim007!

**Comment by jillr** [comment]
@caphrim007  Tested and deployed, 61263 now passes against CI when I run it locally.

**Comment by s-hertel** [comment]
FYI, this is now causing shippable errors. https://app.shippable.com/github/ansible/ansible/runs/141595/113/tests

**Pull request merged**
