### PR TITLE
Add permissions for Lightsail static IPs

### PR DESCRIPTION
**Pull request by danielcotton**
For integration tests involving the querying and creation/deletion of Lightsail Static IPs

Per https://github.com/ansible-collections/community.aws/pull/259 I am trying to add the ability to allocate and release Ligthsail Static IPs from within Ansible. These permissions are necessary for integration tests to pass.

### CODE REVIEW

**Comment by danielcotton** [comment]
I'd appreciate it if this could be merged so work can proceed on expanding lightsail functionality in Ansible

**Review by jillr — COMMENTED** [review]
Thanks @danielcotton. The permissions look good when tetsing with your PR but we'll need a new terminator class (like this one: https://github.com/mattclay/aws-terminator/blob/master/aws/terminator/compute.py#L378-L394) to remove static IPs in the event that the test fails for some reason before the `always` block runs.

**Comment by danielcotton** [comment]
Thank you @jillr. I believe I've made the necessary changes.

**Review by jillr — APPROVED** [review]
LGTM, thanks @danielcotton

**Pull request merged**
