### PR TITLE
Refactor IAM policies for size

### PR DESCRIPTION
**Pull request by jillr**
Add a new policy file for app security and move inspector and waf(v2) into it.  Accordingly; make a related terminator file.

Condense ec2:Describe* policies down to a wildcard.  This has the effect of adding numerous new policies but I believe they're ok, having reviewed the current full list of ec2:Describe* actions.

Also adds DMS endpoint support, which has been blocked in #139 waiting on this policy rework.

### CODE REVIEW

**Comment by jillr** [comment]
cc @mattclay In the interest of managing the size of the policies, I'm proposing to use `ec2:Describe*` instead of individual Describe actions.  These are the new policies that would effectively add.  I don't see any obvious issues, what do you think?

DescribeAddressesAttribute
DescribeAggregateIdFormat
DescribeBundleTasks
DescribeBundleTasks
DescribeCapacityReservations
DescribeCarrierGateways
DescribeClassicLinkInstances
DescribeClientVpnAuthorizationRules
DescribeClientVpnConnections
DescribeClientVpnEndpoints
DescribeClientVpnRoutes
DescribeClientVpnTargetNetworks
DescribeCoipPools
DescribeConversionTasks
DescribeElasticGpus
DescribeExportImageTasks
DescribeExportTasks
DescribeFastSnapshotRestores
DescribeFleetHistory
DescribeFleetInstances
DescribeFleets
DescribeFlowLogs
DescribeFpgaImageAttribute
DescribeFpgaImages
DescribeHostReservationOfferings
DescribeHostReservations
DescribeHosts
DescribeIdFormat
DescribeIdentityIdFormat
DescribeImportImageTasks
DescribeImportSnapshotTasks
DescribeInstanceCreditSpecifications
DescribeInstanceEventNotificationAttributes
DescribeInstanceTypeOfferings
DescribeInstanceTypes
DescribeIpv6Pools
DescribeLocalGatewayRouteTableVirtualInterfaceGroupAssociations
DescribeLocalGatewayRouteTableVpcAssociations
DescribeLocalGatewayRouteTables
DescribeLocalGatewayVirtualInterfaceGroups
DescribeLocalGatewayVirtualInterfaces
DescribeLocalGateways
DescribeManagedPrefixLists
DescribeMovingAddresses
DescribeNetworkInsightsAnalyses
DescribeNetworkInsightsPaths
DescribeNetworkInterfaceAttribute
DescribeNetworkInterfacePermissions
DescribePlacementGroups
DescribePrefixLists
DescribePrincipalIdFormat
DescribePublicIpv4Pools
DescribeReservedInstances
DescribeReservedInstancesListings
DescribeReservedInstancesModifications
DescribeReservedInstancesOfferings
DescribeScheduledInstanceAvailability
DescribeScheduledInstances
DescribeSecurityGroupReferences
DescribeSnapshotAttribute
DescribeSpotDatafeedSubscription
DescribeSpotFleetInstances
DescribeSpotFleetRequestHistory
DescribeSpotFleetRequests
DescribeSpotInstanceRequests
DescribeStaleSecurityGroups
DescribeTrafficMirrorFilters
DescribeTrafficMirrorSessions
DescribeTrafficMirrorTargets
DescribeTransitGatewayAttachments
DescribeTransitGatewayConnectPeers
DescribeTransitGatewayConnects
DescribeTransitGatewayMulticastDomains
DescribeTransitGatewayPeeringAttachments
DescribeTransitGatewayRouteTables
DescribeTransitGatewayVpcAttachments
DescribeVolumeAttribute
DescribeVolumeStatus
DescribeVolumesModifications
DescribeVpcEndpointConnectionNotifications
DescribeVpcEndpointServiceConfigurations
DescribeVpcEndpointServicePermissions

**Comment by mattclay** [comment]
@jillr Using `ec2:Describe*` is fine with me. The main downside I see is that we lose track of what describe actions are actually needed. That could be an issue for someone who wants to deploy their own terminator with more fine-grained permissions.

**Comment by tremble** [comment]
It might be good to try and specify a more general policy of where wildcards are permitted here.  This brings us up to 8 Managed Policies attached to the terminator role, out of a hard limit of 10. 

Describe* and List* would be obvious candidates.  With secrets (AWS Secrets, KMS Keys, IAM Certs) accessing the secret itself requires a Get call rather than a Describe call.

**Comment by jillr** [comment]
> @jillr Using `ec2:Describe*` is fine with me. The main downside I see is that we lose track of what describe actions are actually needed. That could be an issue for someone who wants to deploy their own terminator with more fine-grained permissions.

We could link to this PR in the docs, showing what policies were in effect at the time we made the switch.  Alternately we could have an option policy file in the hacking directory.  But it'll get outdated pretty quickly, I don't see how we would reasonably be able to maintain it once we start adding new modules or features.

**Pull request merged**
