### PR TITLE
aws - codepipeline support

### PR DESCRIPTION
**Pull request by kapilt**
for https://github.com/ansible/ansible/pull/47189

### CODE REVIEW

**Comment by stefanhorning** [comment]
I guess we still need the permissions to create a fitting IAM role. See comment in https://github.com/ansible/ansible/pull/47189

Same goes for the aws_code_build_role see https://github.com/ansible/ansible/pull/47187

**Comment by mattclay** [comment]
@kapilt Do you have time to resolve the conflicts on this PR?

**Comment by stefanhorning** [comment]
@mattclay @kapilt opened a new PR here https://github.com/mattclay/aws-terminator/pull/41 without conflicts.

**Comment by mattclay** [comment]
Superseded by https://github.com/mattclay/aws-terminator/pull/41

**Comment by mattclay** [comment]
@kapilt Thanks for the initial work on this. @stefanhorning Thanks for finishing this up.

**Pull request closed without merging**
