### PR TITLE
Add SNS and SQS tagging permissions

### PR DESCRIPTION
**Pull request by tremble**
Attempting to revive #202 so we can get https://github.com/ansible-collections/community.aws/pull/972 or https://github.com/ansible-collections/community.aws/pull/1604 merged.

### CODE REVIEW

**Comment by tremble** [comment]
@gravesm Any chance we can get this merged?  (and close out #202)

**Comment by gravesm** [comment]
Sure, would you mind rebasing https://github.com/ansible-collections/community.aws/pull/972 so I can test against these changes?

**Comment by tremble** [comment]
rebased

**Comment by gravesm** [comment]
I'm still getting the exact same error I got in #202: `not authorized to perform: SNS:ListTagsForResource on resource: arn:aws:sns:us-east-1:806199016981:AmazonIpSpaceChanged because no resource-based policy allows the SNS:ListTagsForResource action`.

I guess I still don't understand how this is supposed to work, but I'm ok with merging this if you think the error is just an artifact of me running this locally.

**Comment by tremble** [comment]
I've just realised why you'll be seeing that.  It's not an artefact of running locally, it's an artefact of the code still trying to read tags.  If you merge it I can fix that issue.

**Review by gravesm — APPROVED** [review]

**Pull request merged**
