### PR TITLE
add rds policy for CopyDBSnapshot

### PR DESCRIPTION
**Pull request by jatorcasso**
needed by https://github.com/ansible-collections/community.aws/pull/1078

### CODE REVIEW

**Comment by jatorcasso** [comment]
recheck

**Comment by gravesm** [comment]
Unless I'm mistaken, I don't think we can support copying a db snapshot to another region, because the terminator is only going to clean up snapshots in us-east-1. @jillr can you confirm?

**Comment by jatorcasso** [comment]
> Unless I'm mistaken, I don't think we can support copying a db snapshot to another region, because the terminator is only going to clean up snapshots in us-east-1. @jillr can you confirm?

ah, okay. that makes sense! If that's the case, I can comment out those integration tests and leave a comment.

**Comment by jatorcasso** [comment]
@gravesm updated integration tests to copy snapshots in the same region 👍🏻

**Review by gravesm — APPROVED** [review]

**Pull request merged**
