### PR TITLE
Update DynamoDB permissions

### PR DESCRIPTION
**Pull request by tremble**
- List/Remove tags
- Manage backups

Attempts to revive #98

I'm working on a boto3 migration (I struggled to follow https://github.com/ansible-collections/community.aws/pull/65 and it's been somewhat mangled in the migration from ansible/ansible to ansible-collections/community.aws so I'm starting with a simple migration)

### CODE REVIEW

**Comment by tremble** [comment]
Tests available at https://github.com/ansible-collections/community.aws/pull/725 that I haven't broken anything, but I wanted to get the permissions lined up while I work locally on dynamodb.

**Review by jillr — COMMENTED** [review]
There's no DynamoDb terminator class today; the existing policies here are to support the use of dynamo in DbTerminator.  We'll need a new terminator class that ignores tables named like `ansible_core_ci_resources_dev` and `ansible_core_ci_resources_prod`.

@mattclay Any other concerns/considerations you'd have for adding terminator coverage for DynamoDb?

**Comment by tremble** [comment]
> There's no DynamoDb terminator class today; the existing policies here are to support the use of dynamo in DbTerminator. We'll need a new terminator class that ignores tables named like `ansible_core_ci_resources_dev` and `ansible_core_ci_resources_prod`.

https://github.com/mattclay/aws-terminator/blob/master/aws/terminator/application_services.py#L328

**Comment by jillr** [comment]
Never mind me, I failed at grep - the terminator class totally exists.

**Review by jillr — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
