### PR TITLE
Add AWS Glue Job permissions

### PR DESCRIPTION
**Pull request by ichekaldin**
This allows AWS Glue integration tests to be executed, per @tremble
recommendation in https://github.com/ansible-collections/community.aws/pull/480

This replaces https://github.com/mattclay/aws-terminator/pull/95 which appears to have been abandoned.

### CODE REVIEW

**Review by jillr — COMMENTED** [review]
Hi @ichekaldin, the policies look good but we'll also need a new class added to the terminator lambda for Glue Jobs. The terminator is a lambda function that runs in our CI account and deletes resources that have been online for longer than a set time, in case a CI job fails to clean up after itself for some reason.

You can see an example of the class for cleaning up glue connections here:
https://github.com/mattclay/aws-terminator/blob/master/aws/terminator/data_services.py#L54-L72

**Comment by ichekaldin** [comment]
@jillr I added the class to cleanup Glue jobs. Thank you!

**Comment by ichekaldin** [comment]
@jillr Is there anything else that I'm missing for this PR?

**Comment by jillr** [comment]
Hi @ichekaldin, apologies for the delay I was out of the office for a bit - I work through this queue and do policy deploys on Thursdays usually.  These seem good but I'm not able to test successfully with 480, I'll leave some comments over there.

**Review by jillr — APPROVED** [review]

**Pull request merged**
